name: Deploy docs site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next
          generator_config_file: ./docs/base.next.config.js

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ./docs/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies in core
        run: npm install
        working-directory: ./core

      - name: Install dependencies in docs
        run: npm install
        working-directory: ./docs

      - name: Build library documentation
        run: npx typedoc --options core-typedoc.json
        working-directory: ./docs

      - name: Build with Next.js
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npx next build
        working-directory: ./docs

      - name: Static HTML export with Next.js
        run: npx next export
        working-directory: ./docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
